spring.application.name=Notes_Management_Api

spring.datasource.url=jdbc:mysql://avnadmin:AVNS_opNg-qeuVkdlMacTauY@mysql-43e4815-notemanagementsystem-97de.k.aivencloud.com:17176/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

jwt.secret.key=${SECRET_KEY}
jwt.expiration=3600000